### PR TITLE
gateway: fix package res, improve response structure standardization

### LINKED ISSUE #131: gateway: package res is busted
So many things wrong with it, ill fix it up soon

### PR DESCRIPTION
**Pull request by bobheadxi**
:tickets: **Ticket(s)**: Closes #131

---

## :construction_worker: Changes

* Remove redundant argument (http request) for response constructors (these are available on `Render()`
* Set request ID on responses
* Streamline structure of `BaseResponse`:

```go
type baseResponse struct {
	// Basic metadata
	HTTPStatusCode int    `json:"code"`
	RequestID      string `json:"request_id,omitempty"`

	// Message is included in all responses, and is a summary of the server's response
	Message string `json:"message"`

	// Err contains additional context in the event of an error
	Err string `json:"error,omitempty"`

	// Data contains information the server wants to return
	Data interface{} `json:"data,omitempty"`
}
```

## :flashlight: Testing Instructions

all tests should pass, changes should not introduce incompatibilities yet

### CODE REVIEW

File: gateway/res/base.go [hunk 1]
```diff
@@ -1,18 +1,86 @@
...
+		var (
+			k = kvs[i].(string)
+			v = kvs[i+1]
+		)
+		if k == "error" {
+			switch err := v.(type) {
+			case error:
+				e = err.Error()
+			case string:
+				e = err
```
Comment (leesw98) [inline gateway/res/base.go]: How are we going to handle when the error will be more detailed than a simple message? It might be better if there is a way the error can be a map of sorts so that error renders as a object.

Relevant: https://jsonapi.org/format/#error-objects

**Review by bwdmonkey — APPROVED** [review]
Otherwise, LGTM

File: gateway/res/base.go (hunk 1 above)
Comment (bobheadxi) [reply gateway/res/base.go]: Golang errors only expose a single string message, to keep them lightweight (this is changing with the [Go 2 Errors Proposal](), but this is life for now)

For more details, provide context in the additional parameters which maps onto data. For example:

```go
res.ErrInternalServer("blah", err,
    "context1", "additional detail",
    "context2", "additional detail 2")
```

```js
{
    // ...
    "error": "blah",
    "data": {
        "context1": "additional detail",
        "context2": "additional detail 2"
    }
}
```

Comment (leesw98) [reply gateway/res/base.go]: Alright. Sounds good!
